//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.1008
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCNC {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class JCNCSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static JCNCSettings defaultInstance = ((JCNCSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new JCNCSettings())));
        
        public static JCNCSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_CLNT_AUTO {
            get {
                return ((bool)(this["FCP_CLNT_AUTO"]));
            }
            set {
                this["FCP_CLNT_AUTO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_CLNT_MAN {
            get {
                return ((bool)(this["FCP_CLNT_MAN"]));
            }
            set {
                this["FCP_CLNT_MAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_CLNT_M01 {
            get {
                return ((bool)(this["FCP_CLNT_M01"]));
            }
            set {
                this["FCP_CLNT_M01"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_AIRBLOW {
            get {
                return ((bool)(this["FCP_AIRBLOW"]));
            }
            set {
                this["FCP_AIRBLOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_CHIPCVY {
            get {
                return ((bool)(this["FCP_CHIPCVY"]));
            }
            set {
                this["FCP_CHIPCVY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_DRYRUN {
            get {
                return ((bool)(this["FCP_DRYRUN"]));
            }
            set {
                this["FCP_DRYRUN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_BDT {
            get {
                return ((bool)(this["FCP_BDT"]));
            }
            set {
                this["FCP_BDT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_MST {
            get {
                return ((bool)(this["FCP_MST"]));
            }
            set {
                this["FCP_MST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_ZLOCK {
            get {
                return ((bool)(this["FCP_ZLOCK"]));
            }
            set {
                this["FCP_ZLOCK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MEM")]
        public string AutoRunOpendFileName {
            get {
                return ((string)(this["AutoRunOpendFileName"]));
            }
            set {
                this["AutoRunOpendFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PPMACLink {
            get {
                return ((bool)(this["PPMACLink"]));
            }
            set {
                this["PPMACLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double SPOverideValue {
            get {
                return ((double)(this["SPOverideValue"]));
            }
            set {
                this["SPOverideValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_WORKLIGHT {
            get {
                return ((bool)(this["FCP_WORKLIGHT"]));
            }
            set {
                this["FCP_WORKLIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_WASHDOWN_ON {
            get {
                return ((bool)(this["FCP_WASHDOWN_ON"]));
            }
            set {
                this["FCP_WASHDOWN_ON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_KNIFECLAMPING_ON {
            get {
                return ((bool)(this["FCP_KNIFECLAMPING_ON"]));
            }
            set {
                this["FCP_KNIFECLAMPING_ON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FCP_MLK_ON {
            get {
                return ((bool)(this["FCP_MLK_ON"]));
            }
            set {
                this["FCP_MLK_ON"] = value;
            }
        }
    }
}
