using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PagesAuthority
{
    public partial class FuncSelPage
    {
        bool MAINLev1_Func1 = MAINLev1.Default.Func01;
        bool MAINLev1_Func2 = MAINLev1.Default.Func02;
        bool MAINLev1_Func3 = MAINLev1.Default.Func03;
        bool MAINLev1_Func4 = MAINLev1.Default.Func04;
        bool MAINLev1_Func5 = MAINLev1.Default.Func05;
        bool MAINLev1_Func6 = MAINLev1.Default.Func06;
        bool MAINLev1_Func7 = MAINLev1.Default.Func07;
        bool MAINLev1_Func8 = MAINLev1.Default.Func08;
        bool MAINLev1_Func9 = MAINLev1.Default.Func09;
        bool MAINLev1_Func10 = MAINLev1.Default.Func10;
        bool MAINLev1_Func11 = MAINLev1.Default.Func11;
        bool MAINLev1_Func12 = MAINLev1.Default.Func12;
        bool MAINLev1_Func13 = MAINLev1.Default.Func13;
        bool MAINLev1_Func14 = MAINLev1.Default.Func14;
        bool MAINLev1_Func15 = MAINLev1.Default.Func15;
        bool MAINLev1_Func16 = MAINLev1.Default.Func16;
        bool MAINLev1_Func17 = MAINLev1.Default.Func17;
        bool MAINLev1_Func18 = MAINLev1.Default.Func18;
        bool MAINLev1_Func19 = MAINLev1.Default.Func19;
        bool MAINLev1_Func20 = MAINLev1.Default.Func20;
        bool MAINLev1_Func21 = MAINLev1.Default.Func21;
        bool MAINLev1_Func22 = MAINLev1.Default.Func22;
        bool MAINLev1_Func23 = MAINLev1.Default.Func23;
        bool MAINLev1_Func24 = MAINLev1.Default.Func24;
        bool MAINLev1_Func25 = MAINLev1.Default.Func25;

        bool MAINLev2_Func1 = MAINLev2.Default.Func01;
        bool MAINLev2_Func2 = MAINLev2.Default.Func02;
        bool MAINLev2_Func3 = MAINLev2.Default.Func03;
        bool MAINLev2_Func4 = MAINLev2.Default.Func04;
        bool MAINLev2_Func5 = MAINLev2.Default.Func05;
        bool MAINLev2_Func6 = MAINLev2.Default.Func06;
        bool MAINLev2_Func7 = MAINLev2.Default.Func07;
        bool MAINLev2_Func8 = MAINLev2.Default.Func08;
        bool MAINLev2_Func9 = MAINLev2.Default.Func09;
        bool MAINLev2_Func10 = MAINLev2.Default.Func10;
        bool MAINLev2_Func11 = MAINLev2.Default.Func11;
        bool MAINLev2_Func12 = MAINLev2.Default.Func12;
        bool MAINLev2_Func13 = MAINLev2.Default.Func13;
        bool MAINLev2_Func14 = MAINLev2.Default.Func14;
        bool MAINLev2_Func15 = MAINLev2.Default.Func15;
        bool MAINLev2_Func16 = MAINLev2.Default.Func16;
        bool MAINLev2_Func17 = MAINLev2.Default.Func17;
        bool MAINLev2_Func18 = MAINLev2.Default.Func18;
        bool MAINLev2_Func19 = MAINLev2.Default.Func19;
        bool MAINLev2_Func20 = MAINLev2.Default.Func20;
        bool MAINLev2_Func21 = MAINLev2.Default.Func21;
        bool MAINLev2_Func22 = MAINLev2.Default.Func22;
        bool MAINLev2_Func23 = MAINLev2.Default.Func23;
        bool MAINLev2_Func24 = MAINLev2.Default.Func24;
        bool MAINLev2_Func25 = MAINLev2.Default.Func25;

        bool MAINLev3_Func1 = MAINLev3.Default.Func01;
        bool MAINLev3_Func2 = MAINLev3.Default.Func02;
        bool MAINLev3_Func3 = MAINLev3.Default.Func03;
        bool MAINLev3_Func4 = MAINLev3.Default.Func04;
        bool MAINLev3_Func5 = MAINLev3.Default.Func05;
        bool MAINLev3_Func6 = MAINLev3.Default.Func06;
        bool MAINLev3_Func7 = MAINLev3.Default.Func07;
        bool MAINLev3_Func8 = MAINLev3.Default.Func08;
        bool MAINLev3_Func9 = MAINLev3.Default.Func09;
        bool MAINLev3_Func10 = MAINLev3.Default.Func10;
        bool MAINLev3_Func11 = MAINLev3.Default.Func11;
        bool MAINLev3_Func12 = MAINLev3.Default.Func12;
        bool MAINLev3_Func13 = MAINLev3.Default.Func13;
        bool MAINLev3_Func14 = MAINLev3.Default.Func14;
        bool MAINLev3_Func15 = MAINLev3.Default.Func15;
        bool MAINLev3_Func16 = MAINLev3.Default.Func16;
        bool MAINLev3_Func17 = MAINLev3.Default.Func17;
        bool MAINLev3_Func18 = MAINLev3.Default.Func18;
        bool MAINLev3_Func19 = MAINLev3.Default.Func19;
        bool MAINLev3_Func20 = MAINLev3.Default.Func20;
        bool MAINLev3_Func21 = MAINLev3.Default.Func21;
        bool MAINLev3_Func22 = MAINLev3.Default.Func22;
        bool MAINLev3_Func23 = MAINLev3.Default.Func23;
        bool MAINLev3_Func24 = MAINLev3.Default.Func24;
        bool MAINLev3_Func25 = MAINLev3.Default.Func25;

        bool MAINLev4_Func1 = MAINLev4.Default.Func01;
        bool MAINLev4_Func2 = MAINLev4.Default.Func02;
        bool MAINLev4_Func3 = MAINLev4.Default.Func03;
        bool MAINLev4_Func4 = MAINLev4.Default.Func04;
        bool MAINLev4_Func5 = MAINLev4.Default.Func05;
        bool MAINLev4_Func6 = MAINLev4.Default.Func06;
        bool MAINLev4_Func7 = MAINLev4.Default.Func07;
        bool MAINLev4_Func8 = MAINLev4.Default.Func08;
        bool MAINLev4_Func9 = MAINLev4.Default.Func09;
        bool MAINLev4_Func10 = MAINLev4.Default.Func10;
        bool MAINLev4_Func11 = MAINLev4.Default.Func11;
        bool MAINLev4_Func12 = MAINLev4.Default.Func12;
        bool MAINLev4_Func13 = MAINLev4.Default.Func13;
        bool MAINLev4_Func14 = MAINLev4.Default.Func14;
        bool MAINLev4_Func15 = MAINLev4.Default.Func15;
        bool MAINLev4_Func16 = MAINLev4.Default.Func16;
        bool MAINLev4_Func17 = MAINLev4.Default.Func17;
        bool MAINLev4_Func18 = MAINLev4.Default.Func18;
        bool MAINLev4_Func19 = MAINLev4.Default.Func19;
        bool MAINLev4_Func20 = MAINLev4.Default.Func20;
        bool MAINLev4_Func21 = MAINLev4.Default.Func21;
        bool MAINLev4_Func22 = MAINLev4.Default.Func22;
        bool MAINLev4_Func23 = MAINLev4.Default.Func23;
        bool MAINLev4_Func24 = MAINLev4.Default.Func24;
        bool MAINLev4_Func25 = MAINLev4.Default.Func25;

        bool MAINLev5_Func1 = MAINLev5.Default.Func01;
        bool MAINLev5_Func2 = MAINLev5.Default.Func02;
        bool MAINLev5_Func3 = MAINLev5.Default.Func03;
        bool MAINLev5_Func4 = MAINLev5.Default.Func04;
        bool MAINLev5_Func5 = MAINLev5.Default.Func05;
        bool MAINLev5_Func6 = MAINLev5.Default.Func06;
        bool MAINLev5_Func7 = MAINLev5.Default.Func07;
        bool MAINLev5_Func8 = MAINLev5.Default.Func08;
        bool MAINLev5_Func9 = MAINLev5.Default.Func09;
        bool MAINLev5_Func10 = MAINLev5.Default.Func10;
        bool MAINLev5_Func11 = MAINLev5.Default.Func11;
        bool MAINLev5_Func12 = MAINLev5.Default.Func12;
        bool MAINLev5_Func13 = MAINLev5.Default.Func13;
        bool MAINLev5_Func14 = MAINLev5.Default.Func14;
        bool MAINLev5_Func15 = MAINLev5.Default.Func15;
        bool MAINLev5_Func16 = MAINLev5.Default.Func16;
        bool MAINLev5_Func17 = MAINLev5.Default.Func17;
        bool MAINLev5_Func18 = MAINLev5.Default.Func18;
        bool MAINLev5_Func19 = MAINLev5.Default.Func19;
        bool MAINLev5_Func20 = MAINLev5.Default.Func20;
        bool MAINLev5_Func21 = MAINLev5.Default.Func21;
        bool MAINLev5_Func22 = MAINLev5.Default.Func22;
        bool MAINLev5_Func23 = MAINLev5.Default.Func23;
        bool MAINLev5_Func24 = MAINLev5.Default.Func24;
        bool MAINLev5_Func25 = MAINLev5.Default.Func25;

        bool MAINLev6_Func1 = MAINLev6.Default.Func01;
        bool MAINLev6_Func2 = MAINLev6.Default.Func02;
        bool MAINLev6_Func3 = MAINLev6.Default.Func03;
        bool MAINLev6_Func4 = MAINLev6.Default.Func04;
        bool MAINLev6_Func5 = MAINLev6.Default.Func05;
        bool MAINLev6_Func6 = MAINLev6.Default.Func06;
        bool MAINLev6_Func7 = MAINLev6.Default.Func07;
        bool MAINLev6_Func8 = MAINLev6.Default.Func08;
        bool MAINLev6_Func9 = MAINLev6.Default.Func09;
        bool MAINLev6_Func10 = MAINLev6.Default.Func10;
        bool MAINLev6_Func11 = MAINLev6.Default.Func11;
        bool MAINLev6_Func12 = MAINLev6.Default.Func12;
        bool MAINLev6_Func13 = MAINLev6.Default.Func13;
        bool MAINLev6_Func14 = MAINLev6.Default.Func14;
        bool MAINLev6_Func15 = MAINLev6.Default.Func15;
        bool MAINLev6_Func16 = MAINLev6.Default.Func16;
        bool MAINLev6_Func17 = MAINLev6.Default.Func17;
        bool MAINLev6_Func18 = MAINLev6.Default.Func18;
        bool MAINLev6_Func19 = MAINLev6.Default.Func19;
        bool MAINLev6_Func20 = MAINLev6.Default.Func20;
        bool MAINLev6_Func21 = MAINLev6.Default.Func21;
        bool MAINLev6_Func22 = MAINLev6.Default.Func22;
        bool MAINLev6_Func23 = MAINLev6.Default.Func23;
        bool MAINLev6_Func24 = MAINLev6.Default.Func24;
        bool MAINLev6_Func25 = MAINLev6.Default.Func25;

    }
}
