using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PagesAuthority
{
    public partial class FuncSelPage
    {
        bool PROGLev1_Func1 = PROGLev1.Default.Func01;
        bool PROGLev1_Func2 = PROGLev1.Default.Func02;
        bool PROGLev1_Func3 = PROGLev1.Default.Func03;
        bool PROGLev1_Func4 = PROGLev1.Default.Func04;
        bool PROGLev1_Func5 = PROGLev1.Default.Func05;
        bool PROGLev1_Func6 = PROGLev1.Default.Func06;
        bool PROGLev1_Func7 = PROGLev1.Default.Func07;
        bool PROGLev1_Func8 = PROGLev1.Default.Func08;
        bool PROGLev1_Func9 = PROGLev1.Default.Func09;
        bool PROGLev1_Func10 = PROGLev1.Default.Func10;
        bool PROGLev1_Func11 = PROGLev1.Default.Func11;
        bool PROGLev1_Func12 = PROGLev1.Default.Func12;
        bool PROGLev1_Func13 = PROGLev1.Default.Func13;
        bool PROGLev1_Func14 = PROGLev1.Default.Func14;
        bool PROGLev1_Func15 = PROGLev1.Default.Func15;
        bool PROGLev1_Func16 = PROGLev1.Default.Func16;
        bool PROGLev1_Func17 = PROGLev1.Default.Func17;
        bool PROGLev1_Func18 = PROGLev1.Default.Func18;
        bool PROGLev1_Func19 = PROGLev1.Default.Func19;
        bool PROGLev1_Func20 = PROGLev1.Default.Func20;
        bool PROGLev1_Func21 = PROGLev1.Default.Func21;
        bool PROGLev1_Func22 = PROGLev1.Default.Func22;
        bool PROGLev1_Func23 = PROGLev1.Default.Func23;
        bool PROGLev1_Func24 = PROGLev1.Default.Func24;
        bool PROGLev1_Func25 = PROGLev1.Default.Func25;

        bool PROGLev2_Func1 = PROGLev2.Default.Func01;
        bool PROGLev2_Func2 = PROGLev2.Default.Func02;
        bool PROGLev2_Func3 = PROGLev2.Default.Func03;
        bool PROGLev2_Func4 = PROGLev2.Default.Func04;
        bool PROGLev2_Func5 = PROGLev2.Default.Func05;
        bool PROGLev2_Func6 = PROGLev2.Default.Func06;
        bool PROGLev2_Func7 = PROGLev2.Default.Func07;
        bool PROGLev2_Func8 = PROGLev2.Default.Func08;
        bool PROGLev2_Func9 = PROGLev2.Default.Func09;
        bool PROGLev2_Func10 = PROGLev2.Default.Func10;
        bool PROGLev2_Func11 = PROGLev2.Default.Func11;
        bool PROGLev2_Func12 = PROGLev2.Default.Func12;
        bool PROGLev2_Func13 = PROGLev2.Default.Func13;
        bool PROGLev2_Func14 = PROGLev2.Default.Func14;
        bool PROGLev2_Func15 = PROGLev2.Default.Func15;
        bool PROGLev2_Func16 = PROGLev2.Default.Func16;
        bool PROGLev2_Func17 = PROGLev2.Default.Func17;
        bool PROGLev2_Func18 = PROGLev2.Default.Func18;
        bool PROGLev2_Func19 = PROGLev2.Default.Func19;
        bool PROGLev2_Func20 = PROGLev2.Default.Func20;
        bool PROGLev2_Func21 = PROGLev2.Default.Func21;
        bool PROGLev2_Func22 = PROGLev2.Default.Func22;
        bool PROGLev2_Func23 = PROGLev2.Default.Func23;
        bool PROGLev2_Func24 = PROGLev2.Default.Func24;
        bool PROGLev2_Func25 = PROGLev2.Default.Func25;

        bool PROGLev3_Func1 = PROGLev3.Default.Func01;
        bool PROGLev3_Func2 = PROGLev3.Default.Func02;
        bool PROGLev3_Func3 = PROGLev3.Default.Func03;
        bool PROGLev3_Func4 = PROGLev3.Default.Func04;
        bool PROGLev3_Func5 = PROGLev3.Default.Func05;
        bool PROGLev3_Func6 = PROGLev3.Default.Func06;
        bool PROGLev3_Func7 = PROGLev3.Default.Func07;
        bool PROGLev3_Func8 = PROGLev3.Default.Func08;
        bool PROGLev3_Func9 = PROGLev3.Default.Func09;
        bool PROGLev3_Func10 = PROGLev3.Default.Func10;
        bool PROGLev3_Func11 = PROGLev3.Default.Func11;
        bool PROGLev3_Func12 = PROGLev3.Default.Func12;
        bool PROGLev3_Func13 = PROGLev3.Default.Func13;
        bool PROGLev3_Func14 = PROGLev3.Default.Func14;
        bool PROGLev3_Func15 = PROGLev3.Default.Func15;
        bool PROGLev3_Func16 = PROGLev3.Default.Func16;
        bool PROGLev3_Func17 = PROGLev3.Default.Func17;
        bool PROGLev3_Func18 = PROGLev3.Default.Func18;
        bool PROGLev3_Func19 = PROGLev3.Default.Func19;
        bool PROGLev3_Func20 = PROGLev3.Default.Func20;
        bool PROGLev3_Func21 = PROGLev3.Default.Func21;
        bool PROGLev3_Func22 = PROGLev3.Default.Func22;
        bool PROGLev3_Func23 = PROGLev3.Default.Func23;
        bool PROGLev3_Func24 = PROGLev3.Default.Func24;
        bool PROGLev3_Func25 = PROGLev3.Default.Func25;

        bool PROGLev4_Func1 = PROGLev4.Default.Func01;
        bool PROGLev4_Func2 = PROGLev4.Default.Func02;
        bool PROGLev4_Func3 = PROGLev4.Default.Func03;
        bool PROGLev4_Func4 = PROGLev4.Default.Func04;
        bool PROGLev4_Func5 = PROGLev4.Default.Func05;
        bool PROGLev4_Func6 = PROGLev4.Default.Func06;
        bool PROGLev4_Func7 = PROGLev4.Default.Func07;
        bool PROGLev4_Func8 = PROGLev4.Default.Func08;
        bool PROGLev4_Func9 = PROGLev4.Default.Func09;
        bool PROGLev4_Func10 = PROGLev4.Default.Func10;
        bool PROGLev4_Func11 = PROGLev4.Default.Func11;
        bool PROGLev4_Func12 = PROGLev4.Default.Func12;
        bool PROGLev4_Func13 = PROGLev4.Default.Func13;
        bool PROGLev4_Func14 = PROGLev4.Default.Func14;
        bool PROGLev4_Func15 = PROGLev4.Default.Func15;
        bool PROGLev4_Func16 = PROGLev4.Default.Func16;
        bool PROGLev4_Func17 = PROGLev4.Default.Func17;
        bool PROGLev4_Func18 = PROGLev4.Default.Func18;
        bool PROGLev4_Func19 = PROGLev4.Default.Func19;
        bool PROGLev4_Func20 = PROGLev4.Default.Func20;
        bool PROGLev4_Func21 = PROGLev4.Default.Func21;
        bool PROGLev4_Func22 = PROGLev4.Default.Func22;
        bool PROGLev4_Func23 = PROGLev4.Default.Func23;
        bool PROGLev4_Func24 = PROGLev4.Default.Func24;
        bool PROGLev4_Func25 = PROGLev4.Default.Func25;

        bool PROGLev5_Func1 = PROGLev5.Default.Func01;
        bool PROGLev5_Func2 = PROGLev5.Default.Func02;
        bool PROGLev5_Func3 = PROGLev5.Default.Func03;
        bool PROGLev5_Func4 = PROGLev5.Default.Func04;
        bool PROGLev5_Func5 = PROGLev5.Default.Func05;
        bool PROGLev5_Func6 = PROGLev5.Default.Func06;
        bool PROGLev5_Func7 = PROGLev5.Default.Func07;
        bool PROGLev5_Func8 = PROGLev5.Default.Func08;
        bool PROGLev5_Func9 = PROGLev5.Default.Func09;
        bool PROGLev5_Func10 = PROGLev5.Default.Func10;
        bool PROGLev5_Func11 = PROGLev5.Default.Func11;
        bool PROGLev5_Func12 = PROGLev5.Default.Func12;
        bool PROGLev5_Func13 = PROGLev5.Default.Func13;
        bool PROGLev5_Func14 = PROGLev5.Default.Func14;
        bool PROGLev5_Func15 = PROGLev5.Default.Func15;
        bool PROGLev5_Func16 = PROGLev5.Default.Func16;
        bool PROGLev5_Func17 = PROGLev5.Default.Func17;
        bool PROGLev5_Func18 = PROGLev5.Default.Func18;
        bool PROGLev5_Func19 = PROGLev5.Default.Func19;
        bool PROGLev5_Func20 = PROGLev5.Default.Func20;
        bool PROGLev5_Func21 = PROGLev5.Default.Func21;
        bool PROGLev5_Func22 = PROGLev5.Default.Func22;
        bool PROGLev5_Func23 = PROGLev5.Default.Func23;
        bool PROGLev5_Func24 = PROGLev5.Default.Func24;
        bool PROGLev5_Func25 = PROGLev5.Default.Func25;

        bool PROGLev6_Func1 = PROGLev6.Default.Func01;
        bool PROGLev6_Func2 = PROGLev6.Default.Func02;
        bool PROGLev6_Func3 = PROGLev6.Default.Func03;
        bool PROGLev6_Func4 = PROGLev6.Default.Func04;
        bool PROGLev6_Func5 = PROGLev6.Default.Func05;
        bool PROGLev6_Func6 = PROGLev6.Default.Func06;
        bool PROGLev6_Func7 = PROGLev6.Default.Func07;
        bool PROGLev6_Func8 = PROGLev6.Default.Func08;
        bool PROGLev6_Func9 = PROGLev6.Default.Func09;
        bool PROGLev6_Func10 = PROGLev6.Default.Func10;
        bool PROGLev6_Func11 = PROGLev6.Default.Func11;
        bool PROGLev6_Func12 = PROGLev6.Default.Func12;
        bool PROGLev6_Func13 = PROGLev6.Default.Func13;
        bool PROGLev6_Func14 = PROGLev6.Default.Func14;
        bool PROGLev6_Func15 = PROGLev6.Default.Func15;
        bool PROGLev6_Func16 = PROGLev6.Default.Func16;
        bool PROGLev6_Func17 = PROGLev6.Default.Func17;
        bool PROGLev6_Func18 = PROGLev6.Default.Func18;
        bool PROGLev6_Func19 = PROGLev6.Default.Func19;
        bool PROGLev6_Func20 = PROGLev6.Default.Func20;
        bool PROGLev6_Func21 = PROGLev6.Default.Func21;
        bool PROGLev6_Func22 = PROGLev6.Default.Func22;
        bool PROGLev6_Func23 = PROGLev6.Default.Func23;
        bool PROGLev6_Func24 = PROGLev6.Default.Func24;
        bool PROGLev6_Func25 = PROGLev6.Default.Func25;

    }
}
