//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.296
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCNCShareMemory {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class ShareMemorySet : global::System.Configuration.ApplicationSettingsBase {
        
        private static ShareMemorySet defaultInstance = ((ShareMemorySet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ShareMemorySet())));
        
        public static ShareMemorySet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime SystDateTime {
            get {
                return ((global::System.DateTime)(this["SystDateTime"]));
            }
            set {
                this["SystDateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime PowerOnTime {
            get {
                return ((global::System.DateTime)(this["PowerOnTime"]));
            }
            set {
                this["PowerOnTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("104857.6")]
        public double ElectricalGearRatio {
            get {
                return ((double)(this["ElectricalGearRatio"]));
            }
            set {
                this["ElectricalGearRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.TimeSpan AutoOperateTimeSpan {
            get {
                return ((global::System.TimeSpan)(this["AutoOperateTimeSpan"]));
            }
            set {
                this["AutoOperateTimeSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15000")]
        public int MaxFeedRate {
            get {
                return ((int)(this["MaxFeedRate"]));
            }
            set {
                this["MaxFeedRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54")]
        public double CurrentCoordinateSystem {
            get {
                return ((double)(this["CurrentCoordinateSystem"]));
            }
            set {
                this["CurrentCoordinateSystem"] = value;
            }
        }
    }
}
