//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.296
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOGSetUpUI {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class JOGSet : global::System.Configuration.ApplicationSettingsBase {
        
        private static JOGSet defaultInstance = ((JOGSet)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new JOGSet())));
        
        public static JOGSet Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double JogFeedrate {
            get {
                return ((double)(this["JogFeedrate"]));
            }
            set {
                this["JogFeedrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IncJog {
            get {
                return ((double)(this["IncJog"]));
            }
            set {
                this["IncJog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24000")]
        public double SpindleSpeed {
            get {
                return ((double)(this["SpindleSpeed"]));
            }
            set {
                this["SpindleSpeed"] = value;
            }
        }
    }
}
